Story integration
housinghq/react-photostory pull request #13
Opened 2016-11-28 07:31 UTC by ritz078

implemented photostory as a higher order component.

2016-11-28 07:31 UTC, ritz078 commented
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://fb5a67cf-39d1-4e55-9a24-57a4ec689004.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/housinghq/react-photostory/branch/story/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

2016-12-09 11:47 UTC, pranjal-jain requested changes

2016-12-09 11:47 UTC, pranjal-jain commented on components/Story.js
> +      pan: null,
Change pan to panImgUrl

2016-12-09 11:47 UTC, pranjal-jain commented on components/Story.js
> +        document.body.style.overflow = this.state.isOpen ? 'hidden' : null
in componentWillUnmount add document.body.style.overflow = null

2016-12-09 11:47 UTC, pranjal-jain commented on components/Story.js
> +    }
data, length, title, subtitle can be moved out of state

2016-12-09 11:47 UTC, pranjal-jain commented on components/Story.js
> +      this.props.onOpen({index, title, subTitle, data})
Check for undefined before calling

2016-12-09 11:47 UTC, pranjal-jain commented on components/Story.js
> +      this.props.onClose({index: this.state.currentIndex})
Check for undefined before calling

2016-12-09 11:47 UTC, pranjal-jain commented on components/Swipe.js
> +    setTimeout(this.setWidth, 0)
setWidth can be called in onOpen callback

2016-12-10 07:48 UTC, ritz078 commented on components/Story.js
> +      this.props.onOpen({index, title, subTitle, data})
not needed. empty function is present in defaultProps

2016-12-10 07:48 UTC, ritz078 commented on components/Story.js
> +      this.props.onClose({index: this.state.currentIndex})
same

2016-12-21 18:21 UTC, merged